export const experienceData = [
  {
    id: 1,
    title: "Senior Web & Visual Designer",
    company: "HealthWorksAI (TEG Analytics)",
    period: "Jul 2021 - Present",
    location: "Remote",
    responsibilities: [
      "Designed and prototyped marketing and product-facing interfaces using Figma and Adobe XD",
      "Built responsive landing pages for campaigns, improving lead generation and engagement",
      "Created visuals and motion assets for analytics dashboards, social media, and web campaigns",
      "Solved UX issues across the analytics portal, enhancing usability and task flows",
      "Wrote clean, reusable HTML/CSS/JS code to support front-end implementation",
      "Developed graphics and animations for web and email, increasing brand recall",
      "Collaborated with marketing and product teams using tools like HubSpot, Jira, and Git",
    ],
    current: true,
  },
  {
    id: 2,
    title: "Frontend Developer & Visual Designer",
    company: "Peridot Creative Studio",
    period: "Jun 2018 - May 2021",
    location: "India",
    responsibilities: [
      "Designed and developed responsive websites and mobile UIs with HTML, CSS, and JavaScript",
      "Built reusable UI components and ensured WCAG accessibility across platforms",
      "Created high-fidelity visuals and marketing assets for digital campaigns and brand identity",
      "Maintained design consistency by aligning with client brand systems and guidelines",
      "Conducted functional testing and debugging to ensure performance and cross-browser compatibility",
      "Collaborated directly with clients to gather feedback, iterate designs, and deliver tailored solutions",
      "Used Git and version control tools to maintain clean and collaborative workflows",
    ],
    current: false,
  },
];
