export const skillsData = [
  {
    category: "UX Skills",
    icon: "FaUserCheck",
    skills: [
      "User Research",
      "Usability Testing",
      "Wireframing",
      "Prototyping",
      "Journey Mapping",
      "A/B Testing",
      "Accessibility (WCAG)",
      "UX Writing",
      "UX Metrics",
      "Information Architecture",
    ],
  },
  {
    category: "UI & Systems",
    icon: "FaPalette",
    skills: [
      "Figma (Components, Tokens, Variables, AI Features)",
      "Design Tokens",
      "Component Libraries",
      "Motion Design",
      "Microinteractions",
      "Responsive Design",
      "Design Systems",
    ],
  },
  {
    category: "AI Tools & Prompting",
    icon: "FaBrain",
    skills: [
      "Lovable",
      "Framer AI",
      "Midjourney",
      "Galileo AI",
      "Uizard",
      "Prompt Engineering",
      "Persona & Copy Generation",
      "ChatGPT (for UX writing, ideation, and research)",
    ],
  },
  {
    category: "Design & Creative Tools",
    icon: "FaPencilRuler",
    skills: [
      "Adobe Creative Suite (Illustrator, Photoshop, XD, After Effects)",
      "FigJam",
      "Miro",
      "Framer",
      "InVision",
    ],
  },
  {
    category: "Front-end & Dev Handoff",
    icon: "FaCode",
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript (ES6)",
      "React",
      "Git",
      "Dev Handoff",
      "Agile",
      "Jira",
      "Trello",
      "Slack",
    ],
  },
];
